### ISSUE TITLE
Authorization is broken

### ISSUE THREAD

**Issue by wirtsi** [stefangabos/Zebra_cURL#19]
Hi

because on the _requests options, the CURLOPT_USERPWD is set to NULL, any user password set in the options will be wiped ... therefore authorization is broken

bests
wirtsi

**Comment by stefangabos** [comment]
Not unless you use the [dedicated method](http://stefangabos.ro/wp-content/docs/Zebra_cURL/Zebra_cURL/Zebra_cURL.html#methodhttp_authentication)

**Comment by wirtsi** [comment]
I am using this method, it is still not working. Only if I remove line 987...

**Comment by stefangabos** [comment]
That's odd...I am using this feature right now on a project, and I've been using it also in the past...

$curl->authentication('username', 'password');
$curl->get('page behind authentication');

It's true I've only used to get past basic HTTP authentication

**Comment by wirtsi** [comment]
Hi .. 
sorry about being so vague, some more details on this:
I'm using 1.3.1.
Code snippet
```
$curl->http_authentication("1", "password") ;
$start = microtime(true);
$curl->get(array(
  urls
));
```

Fails for me. I debugged through the code and came across this:

http_authentication sets $this->options with the 10005 CURL option.
The get function the creates the _requests with 10005 set to null
In _queue_requests there is 
```
foreach ($request['options'] as $key => $value) $this->option($key, $value);
```
Which writes the null value to the options again

**Comment by stefangabos** [comment]
Should be fixed now
