### ISSUE TITLE
Broken images

### ISSUE THREAD

**Issue by Fshamri** [stefangabos/Zebra_cURL#20]
I used your library to download images from internet and have two problems:

1- i just parsed html string to extract image urls i do save those extracted urls in array and then pass it to Zebra_cURL like:  

```
$curl = new Zebra_cURL();
$curl->download( $urls,$save_to, 'callback');
```

sometime the downloaded image appears like: 

![untitled](https://cloud.githubusercontent.com/assets/3888327/10252979/7aff8cce-6943-11e5-85d2-ef26c2b6aa43.png)

i.e image content is partially downloaded.

2-  I am not able to download images if image urls come with  `?itok=FpNAAWYx`     like:

```
http://www.ansar-allah.net/sites/default/files/public/styles/node_image_full/public/11224-1443794907.jpg?itok=FpNAAWYx
```

do i need to set some HEADER option to solve those problems?

Thanks

**Comment by stefangabos** [comment]
For the first problem, you should probably increase the value of CURLOPT_TIMEOUT - which is currently set to 10 seconds

The second problem is now fixed - thanks a lot for reporting!
