### ISSUE TITLE
Callback function on CodeIgniter

### ISSUE THREAD

**Issue by adrianha** [stefangabos/Zebra_cURL#21]
Hello,
I am working with Zebra and CodeIgniter but i have a trouble when defining the callback function.
I've added the function within the controller and also in the file Zebra_cURL.php...
Any ideas how to define the callback function for zebra on CodeIgniter?
Thank you

**Comment by stefangabos** [comment]
I don't use CodeIgniter - have you had any luck with this?

**Comment by adrianha** [comment]
Unfortunately i cant make it using CodeIgniter so i came back using native php
