### ISSUE TITLE
Please don't disable SSL cerrtificate checking by default

### ISSUE THREAD

**Issue by bagder** [stefangabos/Zebra_cURL#22]
https://github.com/stefangabos/Zebra_cURL/blob/master/Zebra_cURL.php#L2176

When using SSL, you should verify the peer's certificate by default to make sure that you're communicating with the server you want to talk to and not a middle man or impostor. Otherwise you will trick users into believing they do secure connections when they're not.

Pointed out to me by Kevin McArthur: https://twitter.com/KevinSMcArthur/status/697536360354172928

**Comment by stefangabos** [comment]
Hmm, I've never thought about it this way...I never actually wanted a secure connection. I'm using this library mostly for scrapping pages and when such a page uses SSL, *not* disabling the checking, 9 out of 10 will break things. So, that's the explanation for those defaults :)

I am open to suggestions, though

**Comment by stefangabos** [comment]
on the bright side, unless you specifically call the ssl() method, curl's defaults will be used

**Comment by stefangabos** [comment]
...and to keep away the mobs with pitchforks, I've changed the defaults

**Comment by bagder** [comment]
:+1:
