### ISSUE TITLE
How do I pass in authentication with a token?

### ISSUE THREAD

**Issue by bbarclay** [stefangabos/Zebra_cURL#30]
Our Api requires that I use a token to pass data in. 

$ curl -H "Content-Type: application/json;" -H "X-Cachet-Token: YOUR_KEY_HERE" -d '{"name":"API","description":"An example description","status":1}' http://status.cachethq.io/api/v1/components

I can't find any class or documentation on how to solve this with Zebra. 

By the way. I love, Zebra. It's the best in my opinion.

**Comment by proclnas** [comment]
Hi @bbarclay! You can try in this way:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

function mycallback($result) {
    var_dump($result);
}

$zebra = new Zebra_cURL;
$zebra->option([CURLOPT_HTTPHEADER => ['X-Cachet-Token: abc']]);
$zebra->get('http://httpbin.org/get', 'mycallback');
```

With that snippet, the cookie has sended to the request:

```
"headers": {
    "Accept": "*/*",
    "Accept-Encoding": "gzip,deflate",
    "Connection": "close",
    "Host": "httpbin.org",
    "User-Agent": "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.2; Win64; x64)",
    "X-Cachet-Token": "abc"
  },
```

;)
