### ISSUE TITLE
Different options per request

### ISSUE THREAD

**Issue by gokaybiz** [stefangabos/Zebra_cURL#32]
I'm using Zebra for the async multi curl requests.
But i need to attach different header data for same links.
How can i do that?

Thanks...

**Comment by AcidRaZor** [comment]
Can you explain more about the different header data you need to add for the same links? It's a bit difficult to understand the requirement.

**Comment by picotrain** [comment]
$customHeaders = array(
						"Content-Type:application/x-www-form-urlencoded",
						"Host:whatever",
						"Accept-Encoding : gzip, deflate",
						"Content-Length:Expect:whatever",
						"Expect:whatever"
					);
					$curl->option(CURLOPT_HTTPHEADER, $customHeaders);

**Comment by gokaybiz** [comment]
I want to change it in second request, and change again in third request etc...

**Comment by stefangabos** [comment]
I am open to suggestions over how to implement this. 
The solution has to be applicable to the other methods also (`get`, `delete`, `put`, etc) and not just for `post`. Also, the solution should be backward compatible. 

Maybe if we come up with a format for URLs - similar to what you've used in your example - say, if the array has the `url`  entry then look for the `headers` entry also and use that if present.

If the array is not of this format then just go the old way

**Comment by stefangabos** [comment]
Ok, I think I got it. The solution has to allow `any` cURL options to be set not just the ones for headers. Therefore, we'll pass an array like 
```php

array(
    'url'       =>  'http://whatever.com',
    'options'   =>  array(
        // any valid cURL option
        CURLOPT_HEADER  =>  array(
                                'accept: application/json',
                                'X-Token-Foo-Bar: ABC123',
                            ),
    ),
    // for POSTs only
    'post-data' =>  array(),
)
```

**Comment by proclnas** [comment]
@stefangabos, nice! U rock this way!

**Comment by picotrain** [comment]
As yes indeed @gokaybiz , the headers are set in general and need to be set on a per request basis. 

@stefangabos - Will you be doing this shortly? I know you are probably very busy.

**Comment by stefangabos** [comment]
Almost done. I think I will be able to commit the changes later today

**Comment by picotrain** [comment]
This is what I did to make it work in the meantime.
Create $customHeaders as desired.

Add to curl post.
$curl->post($xmlstringer, array($_class, $callback), $customHeaders);

public function post($urls, $callback = '', $customHeaders = '') {  - note new argument

Then add argument to array below:
$this->_requests[] = array(
                'url'               =>  $url,
                'options'           =>  array(
                    CURLINFO_HEADER_OUT     =>  1,
                    CURLOPT_HEADER          =>  1,
                    CURLOPT_NOBODY          =>  0,
                    CURLOPT_POST            =>  1,
                    CURLOPT_POSTFIELDS      =>  $values,
                    CURLOPT_BINARYTRANSFER  =>  null,
                    CURLOPT_CUSTOMREQUEST   =>  null,
                    CURLOPT_HTTPGET         =>  null,
                    CURLOPT_FILE            =>  null,
		   CURLOPT_HTTPHEADER      => $customHeaders
                ),
                'callback'          =>  $callback,
                'arguments'         =>  array_slice(func_get_args(), 2),
            );
        }

**Comment by stefangabos** [comment]
I've updated the code and the documentation. Please download the library again, have a look and let me know if it works.
See the documentation for the [post](https://stefangabos.github.io/Zebra_cURL/Zebra_cURL/Zebra_cURL.html#methodpost) method - scroll down to the _$urls_ argument
