### ISSUE TITLE
Reusing a Zebra cURL object in the callback triggers timeout

### ISSUE THREAD

**Issue by heimpogo** [stefangabos/Zebra_cURL#33]
## Reproduction steps
Run the following minimal example:

    <?php
    require_once 'third_party/Zebra_cURL.php';

    $curl = new Zebra_cURL();
    $curl->get('http://www.example.com', function () use ($curl) {
        echo "Call 1 finished.\n";
        $curl->get('http://www.example.net', function () {
            echo "Call 2 finished.\n";
        });
    });

    ?>

## Expected Result
No error should be triggered.

## Actual Result
> Fatal error: Maximum execution time of 30 seconds exceeded in /usr/share/nginx/html/maps/api/third_party/Zebra_cURL.php on line 2439

**Comment by fanopolis** [comment]
I'm getting this error too. 

@stefangabos do you have a solution for it?

**Comment by stefangabos** [comment]
no, but don't do that as it defeats the purpose
see [this](https://github.com/stefangabos/Zebra_cURL/issues/34#issuecomment-489538919) on how to add requests to a queue

**Comment by fanopolis** [comment]
Thanks, makes sense.

**Comment by kezenwa** [comment]
Hello

Sorry for the off-topic comment but does this script use Promises ?
Am kinda new to these whole ASYNC requests of a thing and have read a lot on Promises that I just want to know if these Script uses and/ or returns promises

**Comment by kezenwa** [comment]
> ## Reproduction steps
> Run the following minimal example:
> 
> ```
> <?php
> require_once 'third_party/Zebra_cURL.php';
> 
> $curl = new Zebra_cURL();
> $curl->get('http://www.example.com', function () use ($curl) {
>     echo "Call 1 finished.\n";
>     $curl->get('http://www.example.net', function () {
>         echo "Call 2 finished.\n";
>     });
> });
> 
> ?>
> ```
> 
> ## Expected Result
> No error should be triggered.
> 
> ## Actual Result
> > Fatal error: Maximum execution time of 30 seconds exceeded in /usr/share/nginx/html/maps/api/third_party/Zebra_cURL.php on line 2439

This issue ought to have been closed since it's been rectified

**Comment by stefangabos** [comment]
see [my comment above](https://github.com/stefangabos/Zebra_cURL/issues/33#issuecomment-766366912)
