### ISSUE TITLE
Non-blocking asynchronous requests?

### ISSUE THREAD

**Issue by bavohe3648** [stefangabos/Zebra_cURL#36]
Can I use Zebra requests in a non-blocking way such that I can run other code while the requests are processing? 
I believe it's possible to do with PHP but does Zebra allow this? The callback function option will probably have to be discarded in this case.

**Comment by stefangabos** [comment]
while zebra_curl request's are done asynchronously, there is no way of running other code while this is happening - i can't even imagine how that could even be done. what you want is to let zebra_curl run its own thread and your code on a different one. maybe [this](https://stackoverflow.com/questions/13846192/php-threading-call-to-a-php-function-asynchronously) can serve as a starting point

**Comment by bavohe3648** [comment]
> while zebra_curl request's are done asynchronously, there is no way of running other code while this is happening - i can't even imagine how that could even be done. what you want is to let zebra_curl run its own thread and your code on a different one. maybe [this](https://stackoverflow.com/questions/13846192/php-threading-call-to-a-php-function-asynchronously) can serve as a starting point

I was thinking maybe Zebra Curl could use curl_multi_init() and generate a "future" token that could be later used to check if the request has finished processing, sort of like running
curl_multi_exec($ch, $running) to check if mcurl has finished a request. The requests would have to be done without a callback function as I believe that wouldn't be possible without something like pthreads

**Comment by stefangabos** [comment]
but that is exactly how it happens - zebra_curl *does* use `curl_multi_init` and it later checks if the request has finished processing and it *does* use `curl_multi_exec` :)

each request is done in a non-blocking way but that still is different than what you've asked about - running arbitrary code while zebra_curl is doing its thing...

**Comment by stefangabos** [comment]
just to be clear:
running
```php
$curl->get('url1', function($result) { ... });
$curl->get('url2', function($result) { ... });
```
is not asynchronous; the second request has to wait for the first one to finish
but
```php
$curl->get(array('url1', 'url2', 'url3'), function($result) { ... });
```
*is* asynchronous and URLs are processed in parallel and each of them will call the callback function as soon as it finishes.

[here](https://github.com/stefangabos/Zebra_cURL/issues/34#issuecomment-489538919)'s one example of adding URLs to an initial list, on the fly
