### ISSUE TITLE
huge array of URLs leads to many timeout errors

### ISSUE THREAD

**Issue by DanielRuf** [stefangabos/Zebra_cURL#37]
I'm not sure if there is some bug but for me there are only a few requests that go through and many fail at the end.

```
<?php
require_once 'zebra-curl.php';
ini_set('memory_limit', '320M');

// instantiate the class
$curl = new Zebra_cURL();

$urls = file('urls.txt', FILE_IGNORE_NEW_LINES);
check_url($urls, $curl);

function check_url($urls, $curl)
{

    // process given URLs
    // and execute a callback function for each request, as soon as it finishes
    // the callback function receives as argument an object with 4 properties
    // (info, header, body and response)
    $curl->header($urls, function ($result) {

        // everything went well at cURL level
        if ($result->response[1] == CURLE_OK) {

            // if server responded with code 200 (meaning that everything went well)
            // see https://httpstatus.es/ for a list of possible response codes
            if ($result->info['http_code'] == 200) {

                // see all the returned data
                //print_r('<pre>');
                //print_r($result);
                echo $result->info['url'] . "\n";

                // show the server's response code
            }

            // something went wrong
            // ($result still contains all data that could be gathered)
        } else {
            echo "cURL responded with: " . $result->info['url'] . $result->response[0] . "\n";
        }

    });
}

```

**Comment by stefangabos** [comment]
there's no bug, you are just being rejected on the other side because you
are flooding them. it's either the machine cannot respond in time for so
many concurent requests or their ddos firewall kicks in. try with 10, 20,
50 requests at a time, wait for 1-2 seconds and then do the next batch. the
number of requests you can do depends on the machine you are making the
request to

**Comment by DanielRuf** [comment]
> there's no bug, you are just being rejected on the other side because you are flooding them. it's either the machine cannot respond in time for so many concurent requests or their ddos firewall kicks in. try with 10, 20, 50 requests at a time, wait for 1-2 seconds and then do the next batch. the number of requests you can do depends on the machine you are making the request to
> [](#)

Hm, well. It works when I use the following code:

```
xargs -n1 -P 10 curl -o /dev/null --silent --head --write-out '%{url_effective};%{http_code}\n' < urls.txt | tee status.csv
```

So I guess the batching of the requests could be the issue.

**Comment by DanielRuf** [comment]
> there's no bug, you are just being rejected on the other side because you are flooding them. it's either the machine cannot respond in time for so many concurent requests or their ddos firewall kicks in. try with 10, 20, 50 requests at a time, wait for 1-2 seconds and then do the next batch. the number of requests you can do depends on the machine you are making the request to

Is there some setting in ZebraCURL?

**Comment by stefangabos** [comment]
right, now that you're mentioning it, there *could* be something wrong...on the other hand 10 threads with no wait time might seem like infinite calls to the other side. try setting the `pause_interval` to 1 second just to see if it changes anything

**Comment by stefangabos** [comment]
any updates on this?

**Comment by DanielRuf** [comment]
No update so far. I'll close it. I think I need a different approach for 700k URLs. So far the bash script works much better for me.

**Comment by stefangabos** [comment]
can you please email me your txt? i'd like to investigate if there is indeed a bug in my code. thanks

**Comment by DanielRuf** [comment]
> can you please email me your txt? i'd like to investigate if there is indeed a bug in my code. thanks

I can try, but it's 55 MB (will upload it somewhere else) ;-)

**Comment by DanielRuf** [comment]
> can you please email me your txt? i'd like to investigate if there is indeed a bug in my code. thanks

I can try, but it's 55 MB (will upload it somewhere else) ;-)
As far as I remember also the 100k list failed. Only the smaller ones didn't (and I've already increased the memory limit and there are no related errors).

I'll send you an email later today.
