### ISSUE TITLE
Custom header for each request

### ISSUE THREAD

**Issue by barrosa87** [stefangabos/Zebra_cURL#38]
Hi,

I am doing multiple requests using Zebra Curl (using 10 threads)

Is it possible to set different headers to each thread? Or is it only possible to set same header for entire 10 threads?

I would need to change the cookie in each request.

Thank you

**Comment by stefangabos** [comment]
see docs https://stefangabos.github.io/Zebra_cURL/Zebra_cURL/Zebra_cURL.html#methodpost scroll down to the `url` argument
