### ISSUE TITLE
Attempt to run with PHP 8.0.0 reports errors

### ISSUE THREAD

**Issue by oriononair** [stefangabos/Zebra_cURL#40]
Attempt to run $curl->get with PHP 8.0.0 reports error as listed below.

`Fatal error: Uncaught TypeError: preg_replace(): Argument #3 ($subject) must be of type array|string, CurlHandle given in .../stefangabos/zebra_curl/Zebra_cURL.php:2733 Stack trace: #0`

>             // initialize individual cURL handle with the URL
>             $handle = curl_init($request['url']);
> 
>             // get the handle's ID
>             $resource_number = preg_replace('/Resource id #/', '', $handle);

> Curl init functions curl_init, curl_multi_init, and curl_share_init functions returned PHP resources prior to PHP 8. From PHP 8 and forward, curl_init function returns an instance of \CurlHandle class.

**Comment by stefangabos** [comment]
we're already at 8?!
:)
ok, will look into it. 
thanks for reporting!

**Comment by stefangabos** [comment]
i've seen the error, unfortunately i have no idea how to fix it. *everything* works because of the way this was previously implemented in PHP...

**Comment by stefangabos** [comment]
so, previously every `curl_init` request had a unique ID which I was using later to determine which request finished and what callback needed to be fired. `curl_getinfo` is not giving me anything similar and that's where I am stuck currently. any input is apprectiated

**Comment by stefangabos** [comment]
nevermind, i think i found a fix, working on it right now

**Comment by berkayyildi** [comment]
Oh, nice thank you. The library is a little bit confusing to understand in a short time so I could not help you. But I hope you to fix problem. Good luck.

**Comment by berkayyildi** [comment]
It seems okey right now.

**Comment by oriononair** [comment]
Yeah, it seems to be working fine now. Thanks!

**Comment by salimibrogimov** [comment]
How about using the number from var_dump($ch)?
The var_dump gives us something like this: "object(CurlHandle)#468 (0) {}". We could use #468 as the unique array key.

**Comment by stefangabos** [comment]
that is very nice - I wonder why I didn't think of that! just outputting the variable will not get you that number, but this does.
**but**, in order to capture that value I'd have to do it inside an `ob_start()` and `ob_get_clean()` construct which could have a significant negative performance impact overall, mainly if you are doing lots of calls

so, unless something better comes up, the current solution is better in my opinion

but thanks a lot for the feedback and looking forward for more!

**Comment by salimibrogimov** [comment]
Well, I didn't know that we can't save var_dump's output in variable but then while reading the docs I learned about ob_start() and ob_get_clean() which discouraged me to use var_dump. So, I decided to go on with your solution which much simpler.
Thank you!
