### ISSUE TITLE
How To use Use custom HTTP headers?

### ISSUE THREAD

**Issue by guimatheus01** [stefangabos/Zebra_cURL#41]
I am trying to use Use custom HTTP headers, I am using the same data from a common cURL connection that is functional with the application token but here at Zebra it returns me as a 'Token in White'. I tried to find something in the documentation about it but I didn't find it. Could you help me with that?

**Comment by stefangabos** [comment]
```php
// set custom HTTP headers
$curl->option(CURLOPT_HTTPHEADER, [
    'Accept: application/json',
    'X-Token-Foo-Bar: ABC123'   // Pass keys to APIs, for example
]);
```

**Comment by guimatheus01** [comment]
> ```
> // set custom HTTP headers
> $curl->option(CURLOPT_HTTPHEADER, [
>     'Accept: application/json',
>     'X-Token-Foo-Bar: ABC123'   // Pass keys to APIs, for example
> ]);
> ```

Well, I found the problem. I am really using the one you gave me. But I checked the API parameters I'm using and the problem was with authentication. I was using http_authentication () as suggested in the documentation and it didn't work. Then try a direct connection and it looks like it worked using $ curl-> option (CURLOPT_USERPWD, 'username1: password1'); following the parameters here in the documentation for options. Thank you for your attention and congratulations for the work provided here

**Comment by stefangabos** [comment]
It should've worked with `http_authentication` also as what that does is just setting `CURLOPT_USERPWD`
the only issue that i can think of is that maybe the 3rd parameter of `http_authentication` must be something different than the default `CURLAUTH_ANY` - maybe try it `CURLAUTH_BASIC`. see the [docs](https://stefangabos.github.io/Zebra_cURL/Zebra_cURL/Zebra_cURL.html#methodhttp_authentication)

**Comment by guimatheus01** [comment]
> It should've worked with `http_authentication` also as what that does is just setting `CURLOPT_USERPWD`
> the only issue that i can think of is that maybe the 3rd parameter of `http_authentication` must be something different than the default `CURLAUTH_ANY` - maybe try it `CURLAUTH_BASIC`. see the [docs](https://stefangabos.github.io/Zebra_cURL/Zebra_cURL/Zebra_cURL.html#methodhttp_authentication)

Well, with this parameter CURLAUTH_BASIC, it worked perfectly. I appreciate the support. Excellent tool, the caching system helped a lot in the response time of the application I'm using, it's just incredible.

**Comment by stefangabos** [comment]
awsome, I'm glad you found it useful!
