### ISSUE TITLE
Deprecated: Creation of dynamic property Zebra_cURL::$options is deprecated

### ISSUE THREAD

**Issue by MoontoC** [stefangabos/Zebra_cURL#48]
https://php.watch/versions/8.2/dynamic-properties-deprecated

**Comment by stefangabos** [comment]
thanks for the heads up! i will be fixing it over the weekend

**Comment by stefangabos** [comment]
Please let me know if it is ok now.
Thanks!

**Comment by MoontoC** [comment]
It looks better, thank you~
