### ISSUE TITLE
include zebra_cURL in class

### ISSUE THREAD

**Issue by elegance666** [stefangabos/Zebra_cURL#49]
I need to use Zebra_cURL  in another class

```
    public function __construct($url, $username, $password)
    {
        $this->url = $url;
        $this->cookie = __DIR__ . DIRECTORY_SEPARATOR . "cookie.txt";
        require_once('../includes/Zebra_cURL.php');
	$this->curl = new Zebra_cURL();
    }
```
But I have this error:

Fatal error: Uncaught Error: Class '....\Zebra_cURL' not found in 
How can use that?

**Comment by elegance666** [comment]
Also $curl = new Zebra_cURL(); have same error

**Comment by stefangabos** [comment]
it simply means that you don't have the library at `../includes/Zebra_cURL.php`
you are at `echo dirname(__FILE__);`
