### ISSUE TITLE
$zebra_curl->scrap() or should it be $zebra_curl->scrape()

### ISSUE THREAD

**Issue by n0nag0n** [stefangabos/Zebra_cURL#51]
Title says most of it. I didn't know if it was intentional and it was supposed to be missing the `e` or if I'm overthinking this. I just assumed it would be scrape() to scrape something from a get request real quickly or is it scrap as in you get a scrap of what you're requesting.

Maybe we'll meet in the middle with `fetch()` :rofl:

**Comment by stefangabos** [comment]
hah, that's funny!
i've updated everything - there were quite a bunch of spelling errors throughout the source code regarding this
thanks a lot!

**Comment by n0nag0n** [comment]
Thanks for addressing it. I wasn't sure if I was going crazy or not, and great idea to keep backwards compatibility going. I used this in a tutorial I did for the Flight framework. https://dev.to/n0nag0n/building-a-pokemon-api-in-php-a-beginners-guide-3an8

**Comment by stefangabos** [comment]
Looks good!
Thanks again!
