### ISSUE TITLE
File uploads seem to fail with v1.6.3

### ISSUE THREAD

**Issue by frayer-enterprises** [stefangabos/Zebra_cURL#53]
The  updates to the CURLOPT_POSTFIELDS handling of the $values['data'] seems to break the file uploading.  

Instead of leaving the data as a CURLfile object like it did with 1.6.2, it now converts it into a query string 

The server response is indicating that no file is uploaded.

**Comment by stefangabos** [comment]
unfortunately, yes...i forgot about file uploads...
can you please show me how are you setting it up please?

**Comment by frayer-enterprises** [comment]
$curl = new Zebra_cURL();

    $filename = "/var/www/html/wp-content/uploads/temp.csv";

    $curl->post(array(
        "https://www.domain.com => array(
            'file' => '@'.$filename
        )
    ), 'callback_func');

then in the request object, for the option 10015, it is converted into a string

"file%5Bname%5D=%2Fvar%2Fwww%2Fhtml%2Fwp-content%2Fuploads%2Ftemp.csv&file%5Bmime%5D=&file%5Bpostname%5D="

instead of keeping it as a CURLfile object.

**Comment by stefangabos** [comment]
i was trying to fix an issue i had with nested arrays but i went to aggressive with the fix :)
i pushed an update - can you please grab it and test it?

**Comment by frayer-enterprises** [comment]
That does appear to fix the issue with the file uploads

**Comment by stefangabos** [comment]
i am not satisfied with the result though
let me work on it a little bit more and i'll push a new version in an hour or so with the fix
thanks a lot for the feedback!

**Comment by stefangabos** [comment]
i released 1.6.4 with a better fix (hopefully)

**Comment by stefangabos** [comment]
is this ok, can it be closed?

**Comment by frayer-enterprises** [comment]
Yes it has been resolved.

.[Frayer-Enterprises-Logo.png]
.[cid:e8b1a4ab-a8ad-478a-af59-17ba7ce16aff]
Travis Shaner
System Admin
P <tel:(405)%20984-4551> (405) 984-4551<tel:(405)%20984-4551> | F (405) 347-7257<tel:(405)%20347-7257>
E ***@***.***> ***@***.******@***.***> | https://www.frayerenterprises.com
PO Box 892220 | Oklahoma City, OK | 73189, USA

NOTICE: This message may contain information that is privileged, confidential, or proprietary. If you received this message in error, please notify the sender by reply email or telephone at (405) 984-4551<tel:(405)%20984-4551> and delete the message and any attachments immediately. Any use, review, distribution, retransmission, or reproduction of this message or any attachment by an unintended recipient is prohibited.

.

________________________________
